"""
TOMLFile helper for ppm.
Copyright (c) 2026 Alan. All Rights Reserved.
"""

import datetime
import re
import tomllib  # Used strictly to self-validate our output


class TOMLValue:
    """Formats Python primitives into valid structural TOML data types."""

    @staticmethod
    def format(value) -> str:
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, (int, float)):
            return str(value)
        if isinstance(value, (datetime.datetime, datetime.date)):
            return value.isoformat()
        if isinstance(value, str):
            # Escape backslashes, quotes, and newlines safely
            escaped = (
                value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
            )
            return f'"{escaped}"'
        if isinstance(value, list):
            items = ", ".join(TOMLValue.format(v) for v in value)
            return f"[{items}]"
        raise TypeError(f"Unsupported lock file primitive: {type(value)}")


class TOMLTable:
    """Represents a standard TOML [table] section."""

    def __init__(self, name: str):
        self.name = name
        self.pairs = {}

    def add(self, key: str, value):
        self.pairs[key] = value
        return self

    def render(self) -> str:
        lines = [f"[{self.name}]"]
        for k, v in self.pairs.items():
            lines.append(f"{k} = {TOMLValue.format(v)}")
        return "\n".join(lines)


class TOMLArrayOfTables:
    """Represents a repeating [[array_of_tables]] structure."""

    def __init__(self, name: str):
        self.name = name
        self.entries = []

    def create_entry(self) -> TOMLTable:
        # Create an entry but intentionally don't prefix with [name] manually
        entry = TOMLTable(self.name)
        self.entries.append(entry)
        return entry

    def render(self) -> str:
        blocks = []
        for entry in self.entries:
            lines = [f"[[{self.name}]]"]
            for k, v in entry.pairs.items():
                lines.append(f"{k} = {TOMLValue.format(v)}")
            blocks.append("\n".join(lines))
        return "\n\n".join(blocks)


class TOMLDocument:
    """The root file architect assembling tables and metadata layers."""

    def __init__(self):
        self.root_pairs = {}
        self.sections = []

    def set_global(self, key: str, value):
        self.root_pairs[key] = value
        return self

    def add_table(self, table: TOMLTable):
        self.sections.append(table)
        return table

    def add_array(self, array: TOMLArrayOfTables):
        self.sections.append(array)
        return array

    def render(self, dontwrite_dontedit=False) -> str:
        if dontwrite_dontedit:
            output = ["# Generated by ppm.\n"]
        else:
            output = ["# Generated by ppm. Do not edit directly.\n"]

        # Render root/global configurations first
        for k, v in self.root_pairs.items():
            output.append(f"{k} = {TOMLValue.format(v)}")

        if self.root_pairs:
            output.append("")

        # Render explicit sections
        for section in self.sections:
            output.append(section.render())
            output.append("")  # Spacing

        return "\n".join(output).strip() + "\n"
